
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update
RUN apt-get -y install build-essential curl git
RUN apt-get -y install zlib1g-dev libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt-dev
RUN apt-get -y install rbenv
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
RUN CONFIGURE_OPTS="--disable-install-doc --enable-shared" rbenv install -v 2.4.1

ENV PATH $HOME/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN rbenv global 2.4.1
RUN rbenv exec ruby -v
RUN rbenv exec gem install --no-ri --no-rdoc bundler

RUN mkdir -p /app
ADD Gemfile* /app/
WORKDIR /app

ENV PORT 8080
ENV RACK_ENV production

RUN apt-get -y install pastebinit
RUN rbenv exec bundle install --with=$RACK_ENV

ADD ./ /app

EXPOSE $PORT

CMD rbenv exec bundle exec rackup -p $PORT -E $RACK_ENV 2>&1
