
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update
RUN apt-get install -y wget
RUN echo "deb http://packages.erlang-solutions.com/debian jessie contrib" | tee /etc/apt/sources.list.d/erlang-solutions.list
RUN wget http://packages.erlang-solutions.com/debian/erlang_solutions.asc
RUN apt-key add erlang_solutions.asc

RUN apt-get -y update
RUN apt-get -y install erlang erlang-dev erlang-parsetools elixir pastebinit

# Run NTP to avoid time conflicts that invalidate elixir's CDN certs
RUN apt-get -y install ntp
RUN service ntp start

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez

RUN mkdir -p /app
WORKDIR /app
ADD ./ /app

ENV PORT 8080
ENV MIX_ENV prod
ENV SECRET_KEY_BASE=eventuallythisshouldbeasecret

RUN mix do deps.get, compile, phoenix.digest

EXPOSE 8080

CMD ["mix", "phoenix.server"]
